---
title: "Representativitet"
subtitle: "Fyrtårnprosjektet"
lang: no
language: no-lang.yml
toc: false
format:
  html:
    code-fold: true
    self-contained: true
---

```{r package}
#| output: false
#| echo: false

pkgs <- c("data.table", "fst", "fyr", "ggplot2", "collapse")
if(!require(pak)) install.packages("pacman")
pacman::p_load(char = pkgs)

root <- "~/Git-fhi/analysis/npr/rep"
fx <- list.files(file.path(root, "functions"))
for (i in fx)
  source(file.path(root, "functions", i))

FMD <- data.table::fread(file.path(root, "fmd23.csv"))
SOM <- data.table::fread(file.path(root, "som23.csv"))

som23 <- SOM[!is.na(lopenr)]
fmd23 <- FMD[!is.na(lopenr)]

caseAll <- fyr::count_case(som23, days = 3, acute = T)
case3 <- fyr::count_case(som23[Ft_dummy_Spesialist == 1,], days = 3, acute=T)

DT <- caseAll[dup == 0]
dt <- case3[dup == 0]
```

Nye tilfeller av personskader innen aktivitetsdata for somatikk velges ut på denne måten:

 - Hoveddiagnosekode i ICD10 kapittel XIX, kodene S00-T78.
 - Komplikasjoner og følgetilstander er ikke tatt med.
 - Start av behandling for skadetilfellet i 2023.
 - Planlagt (elektiv) behandling er holdt utenfor.

Et skadetilfelle kan generere flere kontakter med helsevesenet. For å unngå å telle hvert skadetilfelle flere ganger, skal samme skade ikke være mindre enn **3 dager** fra forrige registreringsdato (`innDato`) og at kontakten må være registrert med akutt hastegrad. Dersom pasienten er registrert med flere slike opphold for samme skade på mer enn 3 dager fra forrige registreringsdato, kan samme skade bli telt flere ganger. Det er **`r format(nrow(DT), big.mark = " ")`** skadetilfeller ble registeret i 2023 i hele landet hvor **`r format(nrow(dt), big.mark = " ")`** skadetilfeller er rapportert fra Fyrtårn enhetene.

